Allowed build_deploy_plugin script to remove binary version info when building non-binary plugins.

diff --git a/plugins/frontlinesms-core/do/build_deploy_plugin b/plugins/frontlinesms-core/do/build_deploy_plugin
--- a/plugins/frontlinesms-core/do/build_deploy_plugin
+++ b/plugins/frontlinesms-core/do/build_deploy_plugin
@@ -26,16 +26,24 @@ pluginName=`ls *GrailsPlugin.groovy | cut -d. -f1 | sed -E -e 's/^(.*)GrailsPlug
 echo "# Extracted plugin name as $pluginName"
 
 echo "# Extracting version from application.properties..."
+set +e; grep -q 'version.*binary' *GrailsPlugin.groovy
+binaryVersionSet=$?
+set -e
 if $buildBinary; then
-	set +e; grep -q 'version.*binary' *GrailsPlugin.groovy
-	binaryVersionSet=$?
-	set -e
 	if [[ "$binaryVersionSet" == "1" ]]; then
 		echo "# Changing plugin version to include binary and grails version in the name."
 		sed -E -i -e "s/^\s*def\s+version\s*=\s*['\"](.*?)(-SNAPSHOT)?['\"]\s*$/\tdef version = \"\1-binary-$grailsVersion\2\"/g" *GrailsPlugin.groovy
 	elif [[ "$binaryVersionSet" == "0" ]]; then
 		echo "# Version is already set for binary."
 	else
+		echo "# Error checking if binary version set."
+		exit 1
+	fi
+else
+	if [[ "$binaryVersionSet" == "0" ]]; then
+		echo "# Removing binary info from plugin version..."
+		sed -E -i -e "s/^\s*def\s+version\s*=\s*['\"](.*?)(-binary-$grailsVersion)(-SNAPSHOT)?['\"]\s*$/\tdef version = '\1\3'/" *GrailsPlugin.groovy
+	elif [[ "$binaryVersionSet" != "1" ]]; then
 		echo "# Error checking if binary version set."
 		exit 1
 	fi
