Fixed binary plugin building in build_deploy_plugin

diff --git a/plugins/frontlinesms-core/do/build_deploy_plugin b/plugins/frontlinesms-core/do/build_deploy_plugin
--- a/plugins/frontlinesms-core/do/build_deploy_plugin
+++ b/plugins/frontlinesms-core/do/build_deploy_plugin
@@ -3,51 +3,66 @@ set -e
 
 # Extract flags
 binaryFlag=""
+buildBinary=false
 while [[ $1 == "--"* ]]; do
 	if [ "$1" == "--m2-deploy" ]; then
 		echo "# Maven deployment enabled."
-		M2_DEPLOY=true
+		m2deploy=true
 	fi
 	if [[ "$1" == "--binary" ]]; then
 		echo "# Building plugin as binary."
 		binaryFlag="--binary"
+		buildBinary=true
 	fi
 	shift
 done
 
 echo "# extract app name from application.properties..."
-PLUGIN_NAME=`ls *GrailsPlugin.groovy | cut -d. -f1 | sed -E -e 's/^(.*)GrailsPlugin$/\1/' | sed -E 's/(([^^])([A-Z]))/\2-\3/g' | tr [:upper:] [:lower:]`
-echo "# Extracted plugin name as $PLUGIN_NAME"
+pluginName=`ls *GrailsPlugin.groovy | cut -d. -f1 | sed -E -e 's/^(.*)GrailsPlugin$/\1/' | sed -E 's/(([^^])([A-Z]))/\2-\3/g' | tr [:upper:] [:lower:]`
+echo "# Extracted plugin name as $pluginName"
 
 echo "# extract version from application.properties..."
-PLUGIN_VERSION=$(env groovy -e "`grep -E '^\s*def\s+version' *GrailsPlugin.groovy`; println version")
-echo "# Extracted plugin version as $PLUGIN_VERSION"
+pluginVersion=$(env groovy -e "`grep -E '^\s*def\s+version' *GrailsPlugin.groovy`; println version")
+echo "# Extracted plugin version as $pluginVersion"
 rm plugin.xml || echo "# no plugin.xml present"
 grails --non-interactive clean
 grails --non-interactive --stacktrace $binaryFlag package-plugin
-NEW_PLUGIN_ZIP_NAME=$PLUGIN_NAME-$PLUGIN_VERSION.zip
-OLD_PLUGIN_ZIP_NAME=grails-$NEW_PLUGIN_ZIP_NAME
-echo "# renaming $OLD_PLUGIN_ZIP_NAME to $NEW_PLUGIN_ZIP_NAME"
-mv $OLD_PLUGIN_ZIP_NAME $NEW_PLUGIN_ZIP_NAME
 
-IVY_CACHE_DIR=~/.grails/ivy-cache/org.grails.plugins/$PLUGIN_NAME/zips
-mkdir -p $IVY_CACHE_DIR
-IVY_CACHED_ZIP=$IVY_CACHE_DIR/$NEW_PLUGIN_ZIP_NAME
-echo "# Removing old plugin from local ivy cache at $IVY_CACHED_ZIP..."
-rm $IVY_CACHED_ZIP || echo "# Old plugin was not found in ivy cache."
-echo "# Deploying to local ivy cache..."
-cp $NEW_PLUGIN_ZIP_NAME $IVY_CACHED_ZIP
-echo "# Plugin built and deployed to local ivy cache."
+if $buildBinary; then
+	oldPackageName=target/grails-plugin-$pluginName-$pluginVersion.jar
+	newPackageName=$pluginName-$pluginVersion.jar
+else
+	newPackageName=$pluginName-$pluginVersion.zip
+	oldPackageName=grails-$newPackageName
+fi
+
+echo "# renaming $oldPackageName to $newPackageName"
+mv $oldPackageName $newPackageName
+
+if $buildBinary; then
+	echo "..."
+else
+	ivyCacheDir=~/.grails/ivy-cache/org.grails.plugins/$pluginName/zips
+	mkdir -p $ivyCacheDir
+	ivyCachedZip=$ivyCacheDir/$newPackageName
+	echo "# Removing old plugin from local ivy cache at $ivyCachedZip..."
+	rm $ivyCachedZip || echo "# Old plugin was not found in ivy cache."
+	echo "# Deploying to local ivy cache..."
+	cp $newPackageName $ivyCachedZip
+	echo "# Plugin built and deployed to local ivy cache."
+
+fi
+mavenFileName="$newPackageName"
 
 echo "# Deploying to local maven repository..."
-mavenRepoDir=~/.m2/repository/org/grails/plugins/$PLUGIN_NAME/$PLUGIN_VERSION/
+mavenRepoDir=~/.m2/repository/org/grails/plugins/$pluginName/$pluginVersion/
 echo "# Creating maven repo dir at $mavenRepoDir..."
 mkdir -p $mavenRepoDir
-echo "# Deploying to ${mavenRepoDir}$NEW_PLUGIN_ZIP_NAME..."
-cp $NEW_PLUGIN_ZIP_NAME $mavenRepoDir
+echo "# Deploying to ${mavenRepoDir}$mavenFileName"
+cp $mavenFileName $mavenRepoDir
 echo "# Deployed to local maven repository."
 
-if [ -n "$M2_DEPLOY" ]; then
+if [ -n "$m2deploy" ]; then
 	echo "# deploy core plugin to remote plugin repo"
 	echo "# TODO skip maven deploy for non-SNAPSHOT builds"
 	echo "# Using maven password: $FRONTLINESMS_MAVEN_PASSWORD"
@@ -56,11 +71,11 @@ hash
 user m2repo $FRONTLINESMS_MAVEN_PASSWORD
 mkdir org
 mkdir org/grails/plugins
-mkdir org/grails/plugins/$PLUGIN_NAME
-cd org/grails/plugins/$PLUGIN_NAME
-mkdir $PLUGIN_VERSION
-cd $PLUGIN_VERSION
-put $NEW_PLUGIN_ZIP_NAME
+mkdir org/grails/plugins/$pluginName
+cd org/grails/plugins/$pluginName
+mkdir $pluginVersion
+cd $pluginVersion
+put $mavenFileName
 exit
 EOF
 	echo "# Plugin deployed to remote maven repo."
