Updated build_deploy_plugin to handle bainry POMs and dependencies properly.

diff --git a/plugins/frontlinesms-core/do/build_deploy_plugin b/plugins/frontlinesms-core/do/build_deploy_plugin
--- a/plugins/frontlinesms-core/do/build_deploy_plugin
+++ b/plugins/frontlinesms-core/do/build_deploy_plugin
@@ -21,14 +21,24 @@ echo "# Extracting grails version from application.properties..."
 grailsVersion=$(grep 'app\.grails\.version=' application.properties | cut -d= -f2)
 echo "# Grails version is $grailsVersion"
 
-echo "# extract app name from application.properties..."
+echo "# Extracting app name from application.properties..."
 pluginName=`ls *GrailsPlugin.groovy | cut -d. -f1 | sed -E -e 's/^(.*)GrailsPlugin$/\1/' | sed -E 's/(([^^])([A-Z]))/\2-\3/g' | tr [:upper:] [:lower:]`
 echo "# Extracted plugin name as $pluginName"
 
-echo "# extract version from application.properties..."
+echo "# Extracting version from application.properties..."
 if $buildBinary; then
-	echo "# Changing plugin version to include binary and grails version in the name."
-	sed -E -i -e "s/^\s*def\s+version\s*=\s*['\"](.*?)(-SNAPSHOT)?['\"]\s*$/\tdef version = \"\1-binary-$grailsVersion\2\"/g" *GrailsPlugin.groovy
+	set +e; grep -q 'version.*binary' *GrailsPlugin.groovy
+	binaryVersionSet=$?
+	set -e
+	if [[ "$binaryVersionSet" == "1" ]]; then
+		echo "# Changing plugin version to include binary and grails version in the name."
+		sed -E -i -e "s/^\s*def\s+version\s*=\s*['\"](.*?)(-SNAPSHOT)?['\"]\s*$/\tdef version = \"\1-binary-$grailsVersion\2\"/g" *GrailsPlugin.groovy
+	elif [[ "$binaryVersionSet" == "0" ]]; then
+		echo "# Version is already set for binary."
+	else
+		echo "# Error checking if binary version set."
+		exit 1
+	fi
 fi
 pluginVersion=$(env groovy -e "`grep -E '^\s*def\s+version' *GrailsPlugin.groovy`; println version")
 echo "# Extracted plugin version as $pluginVersion"
@@ -48,7 +58,8 @@ echo "# renaming $oldPackageName to $newPackageName"
 mv $oldPackageName $newPackageName
 
 if $buildBinary; then
-	echo "..."
+	echo "# Building pom file..."
+	grails generate-pom $binaryFlag
 else
 	ivyCacheDir=~/.grails/ivy-cache/org.grails.plugins/$pluginName/zips
 	mkdir -p $ivyCacheDir
@@ -70,9 +81,17 @@ echo "# Deploying to ${mavenRepoDir}$mavenFileName"
 cp $mavenFileName $mavenRepoDir
 echo "# Deployed to local maven repository."
 
+if $buildBinary; then
+	echo "# Deploying POM file to local maven repository..."
+	pomFileName="$pluginName-$pluginVersion.pom"
+	cp target/pom.xml $pomFileName
+	echo "# Deploying to ${mavenRepoDir}$pomFileName"
+	cp $pomFileName ${mavenRepoDir}$pomFileName
+	echo "# POM deployed"
+fi
+
 if [ -n "$m2deploy" ]; then
-	echo "# deploy core plugin to remote plugin repo"
-	echo "# TODO skip maven deploy for non-SNAPSHOT builds"
+	echo "# Deploy core plugin to remote plugin repo..."
 	echo "# Using maven password: $FRONTLINESMS_MAVEN_PASSWORD"
 	ftp -nv dev.frontlinesms.com << EOF
 hash
@@ -84,8 +103,11 @@ cd org/grails/plugins/$pluginName
 mkdir $pluginVersion
 cd $pluginVersion
 put $mavenFileName
+put $pomFileName
 exit
 EOF
 	echo "# Plugin deployed to remote maven repo."
 fi
+
+echo "# Deployment complete."
 
