Alex|Vaneyck Testing build and installation for all users

diff --git a/plugins/frontlinesms-core/do/build_uninstall_install_test b/plugins/frontlinesms-core/do/build_uninstall_install_test
--- a/plugins/frontlinesms-core/do/build_uninstall_install_test
+++ b/plugins/frontlinesms-core/do/build_uninstall_install_test
@@ -11,6 +11,7 @@ echo "## 5. check that the server is working!    ##"
 echo "#############################################"
 
 INSTALL_DIR=~/frontlinesms2
+ALL_USER_INSTALL_DIR=/opt/frontlinesms2
 SETTINGS_DIR=~/.frontlinesms2
 SERVER_PORT=8130
 CONTEXT_PATH=
@@ -26,10 +27,11 @@ grails clean
 grails -Dfrontlinesms2.build.confirmNotProd=true build-installers $@
 
 echo "# uninstall old version"
-$INSTALL_DIR/uninstall -q || echo "# Could not run uninstaller"
+$INSTALL_DIR/uninstall -q || echo "# Could not run uninstaller in $INSTALL_DIR"
+$ALL_USER_INSTALL_DIR/uninstall -q || echo "# Could not run uninstaller in $ALL_USER_INSTALL_DIR"
 
 echo "# remove old install directory"
-rm -rf $INSTALL_DIR/
+rm -rf $INSTALL_DIR/ || rm -rf $ALL_USER_INSTALL_DIR || echo "# Could not remove installation directory as it did not exist"
 
 echo "# remove old settings/database directory"
 rm -rf $SETTINGS_DIR/
@@ -38,7 +40,7 @@ echo "# install new build"
 ../frontlinesms-core/install/target/install4j/*.sh -q || echo "There was an error running the installer TODO supply a valid email address on commandline so this does not fail."
 
 echo "# run new install in background"
-$INSTALL_DIR/*_Launcher &
+$INSTALL_DIR/*_Launcher || $ALL_USER_INSTALL_DIR/*_Launcher &
 LAUNCHER_PROCESS_ID=`jobs -p`
 LAUNCHER_PROCESS_GROUP_ID=`ps -j --pid $LAUNCHER_PROCESS_ID | tail -n1 | grep -Po -m2 "\w+" | grep -Pm2 "\w+" | tail -n1`
 jobs
