Terminate build script if repo is dirty

diff --git a/plugins/frontlinesms-core/do/create_sprint_build b/plugins/frontlinesms-core/do/create_sprint_build
--- a/plugins/frontlinesms-core/do/create_sprint_build
+++ b/plugins/frontlinesms-core/do/create_sprint_build
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+# Abort if git repo is not clean
+if test -n "$(git status --porcelain)"
+then
+	echo "ABORT The sprint build has been terminated due to unclean git repo"
+	exit 1
+fi
+
 # Read sprint number from application.properties
 sprintNumber=`sed '/^\#/d' ./application.properties | grep "sprint.number" | cut -d "=" -f 2`
 echo "Generating build for iteration $sprintNumber"
