added exit status messages to check if the command found matches

diff --git a/plugins/frontlinesms-core/do/g_tag_detector b/plugins/frontlinesms-core/do/g_tag_detector
--- a/plugins/frontlinesms-core/do/g_tag_detector
+++ b/plugins/frontlinesms-core/do/g_tag_detector
@@ -1,2 +1,7 @@
-#grep -rn --color "g:render template" grails-app/views/ grails-app/controllers/
 grep -rn --color 'render template' grails-app/views/ && egrep -rnw --color "(render|g\.render)" grails-app/controllers/
+OUT=$?
+if [ $OUT -eq 0 ];then
+   echo "Matches were found!"
+else
+   echo "Matches were NOT found!"
+fi
