Updated js_unit_test to output node info to stderr.

diff --git a/plugins/frontlinesms-core/do/js_unit_test b/plugins/frontlinesms-core/do/js_unit_test
--- a/plugins/frontlinesms-core/do/js_unit_test
+++ b/plugins/frontlinesms-core/do/js_unit_test
@@ -1,13 +1,18 @@
 #!/bin/bash
-function check_npm_module_available() {
+function err {
+	1>&2 echo "$@"
+}
+
+function check_npm_module_available {
 	MODULE_NAME=$1
-	echo "# Checking for NPM module: $MODULE_NAME..."
+	err "# Checking for NPM module: $MODULE_NAME..."
 	INSTALL_COUNT=`(npm list; npm -g list) | grep -c "^[├└]─[─┬] $MODULE_NAME\@"`
 	if [ 0 -eq $INSTALL_COUNT ]; then
-		echo "# NPM module missing: $MODULE_NAME.  Please run 'npm install $MODULE_NAME' or 'sudo npm i -g $MODULE_NAME'"
-		exit 1
+		err "# NPM module missing: $MODULE_NAME.  To install globally, please run 'sudo npm i -g $MODULE_NAME'"
+		err "# Installing module locally..."
+		npm install $MODULE_NAME
 	fi
-	echo "# NPM Module found: $MODULE_NAME"
+	err "# NPM Module found: $MODULE_NAME"
 }
 check_npm_module_available fs
 check_npm_module_available jquery
