further do/release work

diff --git a/plugins/frontlinesms-core/do/release b/plugins/frontlinesms-core/do/release
--- a/plugins/frontlinesms-core/do/release
+++ b/plugins/frontlinesms-core/do/release
@@ -7,13 +7,24 @@ read -sn 1 -p "## WARNING ## This script will make modifications to your working
 echo ""
 # Read Application.properties to find release version
 APP_VERSION=`sed '/^\#/d' application.properties | grep 'app.version'  | tail -n 1 | cut -d "=" -f2-`
-echo "# Read app version as ${APP_VERSION}"
+echo "# Read current app version as ${APP_VERSION}"
+APP_VERSION_SNAPSHOT_SUBSTRING=${APP_VERSION:(-9)}
 
-# Exit if app version indicates it is an RC
-echo "$APP_VERSION" | grep -qi "rc"
-if [ $? -eq 0 ];
-	then echo "# FAILURE: application version is an RC, must update version number before release" && exit 1
+# Check if app version is recognised
+if [ "$APP_VERSION_SNAPSHOT_SUBSTRING" != "-SNAPSHOT" ];
+	then echo "# FAILURE: application version ending with -SNAPSHOT expected" && exit 1
 fi
+
+# Drop -SNAPSHOT
+APP_VERSION=${APP_VERSION%$APP_VERSION_SNAPSHOT_SUBSTRING}
+echo "after dropping -SNAPSHOT, app version is now ${APP_VERSION}"
+
+# Check if build is an RC
+echo "$app_version" | grep -qi "rc"
+RC_FLAG=$?
+
+# Roll version to new snapshot TODO
+exit 1 # placeholder
 
 # Ensure git repo is clean
 echo "# Checking for clean repository..."
@@ -29,6 +40,9 @@ groovy do/i18n-compare.groovy grails-app/i18n/messages.properties grails-app/i18
 RETVAL=$?
 [ $RETVAL -ne 0 ] && echo "# FAILURE: Swahili translation is incomplete" && exit 1
 echo "# Swahili i18n is complete"
+
+# Drop -SNAPSHOT from application.properties
+sed -i "s/\(app\.version=\).*\$/\1${APP_VERSION}/" application.properties
 
 # Run migration tests
 pushd test/migration
@@ -55,14 +69,12 @@ fi
 # Commit
 echo "Committing and tagging build"
 git add -A
-git commit -m "Built ${APP_VERSION} using do/release script"
+git commit -m "Built ${APP_VERSION} (committed using do/release script)"
 git tag frontlinesms2.$APP_VERSION
 
-# Roll version to new snapshot
-echo "Enter the new snapshot application version for post-build. This should end with '-SNAPSHOT'."
-read POST_BUILD_VERSION
-sed -i "s/\(app\.version=\).*\$/\1${POST_BUILD_VERSION}/" application.properties
-git commit -m "Rolled version numbers to 2.${POST_BUILD_VERSION} after 2.${APP_VERSION} release"
+
+git add -A
+git commit -m "2.${POST_BUILD_VERSION} ready for dev after 2.${APP_VERSION} release (committed using do/release script)"
 
 
 # Upload builds
