added commit step to do/release script

diff --git a/plugins/frontlinesms-core/do/release b/plugins/frontlinesms-core/do/release
--- a/plugins/frontlinesms-core/do/release
+++ b/plugins/frontlinesms-core/do/release
@@ -1,31 +1,46 @@
 #!/bin/bash
-echo "Building new release"
-echo "Checking for clean repository..."
+
+echo "### Building FrontlineSMS v2 release"
+
+# Read Application.properties to find release version
+APP_VERSION=`sed '/^\#/d' application.properties | grep 'app.version'  | tail -n 1 | cut -d "=" -f2-`
+echo "# Read app version as $APP_VERSION"
+
+# Exit if app version indicates it is an RC
+echo "$APP_VERSION" | grep -qi "rc"
+if [ $? -eq 0 ];
+	then echo "# FAILURE: application version is an RC, must update version number before release" && exit 1
+fi
+
+# Ensure git repo is clean
+echo "# Checking for clean repository..."
 if test -n "$(git status --porcelain)"
 then
-	echo "FAILURE: Your repository is not clean. This script can only build from a clean repo"
+	echo "# FAILURE: Your repository is not clean. This script can only build from a clean repo"
 	exit 1
 fi
-# TODO: i18n ? Assert that Kiswahili translation is complete
-echo "Checking for completeness of Kiswahili translation"
+
+# Assert that Kiswahili translation is complete
+echo "# Checking for completeness of Kiswahili translation"
 groovy do/i18n-compare.groovy grails-app/i18n/messages.properties grails-app/i18n/messages_sw.properties
 RETVAL=$?
-[ $RETVAL -ne 0 ] && echo "FAILURE: Swahili translation is incomplete" && exit 1
-echo "Swahili i18n is complete"
+[ $RETVAL -ne 0 ] && echo "# FAILURE: Swahili translation is incomplete" && exit 1
+echo "# Swahili i18n is complete"
 
-# TODO: roll version numbers to non-snapshot
-echo "Rolling version numbers to non-snapshot"
+# Roll version numbers to non-snapshot
+echo "# Rolling version numbers to non-snapshot"
 do/remove_snapshot_from_install_resource_directories
 
-# TODO: do builds
-echo "Building installers.."
+# Do builds
+echo "# Building installers.."
 grails prod BuildInstallers
 
 # TODO: test build in appropriate format for machine
 #### This can reuse elements of build_uninstall_install_test
 
-# TODO: commit
-#### git commit -m "Build for 2.a.b"
+# Commit
+git add -A
+git commit -m "Built $APP_VERSION using do/release script"
 #### git push
 
 # TODO: tag commit
