Added error handling to route SVG generator.

diff --git a/plugins/frontlinesms-core/do/routes_to_svg b/plugins/frontlinesms-core/do/routes_to_svg
--- a/plugins/frontlinesms-core/do/routes_to_svg
+++ b/plugins/frontlinesms-core/do/routes_to_svg
@@ -2,6 +2,14 @@
 set -e
 source bails/head
 
+error_handler() {
+	log "There was an error."
+	log "You may need to install graphviz, e.g."
+	log "	sudo apt-get install graphviz"
+	exit $1
+}
+trap error_handler ERR
+
 launch_browser=false
 while [[ "$1" == --* ]]; do
 	if [[ "$1" == "--launch-browser" ]]; then
