Changed simian_report so that exit code 0 is issued always.  May need to tweak this to interpret simian exit codes more finely.

diff --git a/plugins/frontlinesms-core/do/simian_report b/plugins/frontlinesms-core/do/simian_report
--- a/plugins/frontlinesms-core/do/simian_report
+++ b/plugins/frontlinesms-core/do/simian_report
@@ -12,5 +12,8 @@ fi
 echo "# Using simian jar at: $SIMIAN_JAR..."
 echo "# I hope you've paid for a licence..."
 
+set +e
 java -jar $SIMIAN_JAR $simianFormat -language=groovy "src/groovy/**/*.groovy" "grails-app/**/*.groovy" "test/**/*.groovy"
+echo "# Simian completed with exit code: $?"
+set -e
 
